sudo: false
# cache:
    # apt: true
    # directories:
    # - $HOME/.cache/pip
    # - $HOME/miniconda
    # - $HOME/download

language: python
python:
  # - '2.7'
  - '3.4'
  # - '3.5'
  # - '3.6'
  
env:
  global:
    - FVS_STATUS=alpha
    - BUILD_ROOT=${TRAVIS_BUILD_DIR}/bin/build
    - FVS_VARIANTS="pnc"
    # - FVS_VARIANTS="pnc;wcc;soc;cac;ecc;oc;op"
    
    - TWINE_USERNAME="tod.haren"
    # travis encrypt TWINE_PASSWORD=<plain text> -r tharen/testing
    - secure: "srfuDKb4QWIE5U/u3h7qlsZc/3rokbgAEdagWL5wzrh3MQTqpL8RW0eQFbdp21QD2ZS9CXzeKQDyzqjaMmF5FNE9FqYL3Y66EC9UBhYAqAG6Lf0CbCiBMEK20yHrXyGQ3+bewY4WyTvVidow9pEeW5GdLVZJPTHautKsaNdEXqiqvBUwSNrCtWUVxippka6SizIKI1+yYzlbB/smia4BAOPnw/vkhNhX4iicnADrG+NvPbH6VyXtJqETXTgZ3yFrpa1mTw6isV4HArLSf82puTwPKUWVgOfku0Mmgxcd7RfdvfqO6rMvQH2KtgOyHHCUZqMEX32BGNt1c/fkSrhLpDMZHExUhscePfgyRxCOZE+2QrlcoMjtpZMTWtuYJvk5iNXleGi04jmY5QbAxlaFHjS/En6mnAWH77RkDZoEnO8FxTAXjdPs3Ubq65lr4VhK6VWU4hlbvZyB12lvxZfSm7veE/coFks2YczvZgq95FCNxw57KF4fCxhGqr94R/t3ZVhLRlNp1aMU4xx8VoSza4BhQbAUA2asazQHnbkA3sYd1bnz8vKwGc5t507ktcxCU9WA8w2vFpuBIbvIf5KiyqQFw7SdBso0s45FFdESlY+szGR56g3a3rFlDjIl6jw9ayh4yN0wtI+6gnrIoXBweGt3tK5qb7uqZ+UA+tKd7oU="
    
    - MPLBACKEND="agg"

git:
  depth: 5
  
addons:
  apt:
    sources:
    - george-edison55-precise-backports

    packages:
    - cmake
    - cmake-data
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full

before_install:
  - source .travis-ci/install_miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - hash -r
  # Useful for debugging any issues with conda
  - conda info -a
  # Edit the environment.yml file for the target Python version
  - sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' ./environment.yml
  - conda env create --force -q -n pyfvs -f environment.yml
  
install:
  - source activate pyfvs
  - python -c "import sys;print('{}.{}'.format(*sys.version_info[:2]))"
  # Define the name to be used for the archive of compiled products.
  - export ARCHIVE_NAME=pyfvs-${TRAVIS_TAG}-Python${TRAVIS_PYTHON_VERSION}_64-${TRAVIS_OS_NAME}-ci.zip

script:
  # build.sh compiles the Open-FVS binaries and builds the Python wheel and archive
  - source ${TRAVIS_BUILD_DIR}/.travis-ci/build.sh
  
  # Test the wheel
  - pip install --no-index --find-links ${TRAVIS_BUILD_DIR}/artifacts pyfvs
  - pyfvs --run-tests
  - pytest -rsx --pyargs pyfvs.test
  - conda install matplotlib
  - pytest ${TRAVIS_BUILD_DIR}/python/pyfvs/examples/demo.py
  - pytest ${TRAVIS_BUILD_DIR}/python/pyfvs/examples/pn_test.py

after_failure:
  # Push error logs to the console output
  - "cat ${BUILD_ROOT}/build_err.log"
  - "cat ${BUILD_ROOT}/f2py_pnc.log"

after_success:
  - ls ${TRAVIS_BUILD_DIR}/artifacts
  - conda install twine --yes -c conda-forge
  - chmod +x ${TRAVIS_BUILD_DIR}/.travis-ci/deploy_pypi.sh && ${TRAVIS_BUILD_DIR}/.travis-ci/deploy_pypi.sh
  
deploy:
  # # GitHub Releases
  # - provider: releases
    # skip_cleanup: true
    # prerelease: true
    # api_key:
      # secure: DIF7bPl0y55Q8F8Go0CY40FxN8icu54d2MWRmiuLlGfkeIzcDHHHdJ8W8ZqX/9qyPruWMX/8HvagdKzcLTFC0namicronzZL5XUloR/PGBCT9tRqL3xax36fIHvrmZYIaY7xWIr678s+dG+64lkX5i+BJnt1IDzHjGm+223k3PH/kXRH3NFauPu4PgUszTnIWa+0IBnOhXrodf1A0ljFrtypUleASS19A3PuglHQJRXlDfOpt++M2UHXNBVbhr83jMg8O3XB+BY1QT8g3fYs1kUKmUbxEF6Ab9A/qZtcxIvqK9c55q7sjnaRqvlS5TtQ9ADE1Y97y3hmGNE+xL+x4QCwSC10BGIWvcuVC8Gol/WJY6/EPskNMjKhk9xqhOhqdBiDdyPnLSjhA1zA7e/2mGYwBBw8h9/lvsKvbjHMD47uuKCeDovnB07rYqk6A1bQx4JWAHFwoZB1SuWFT2OcI9aqLE9I/GhiREJgX8I5adJiiqdfLCifSHQINoWUa3b3ZuspFzC+yXIDOwsma5xr7dfMkf+htqofwnzq2R/wM59ryEayfCtdz1VOfrxEnJJfWnL/u9LRbNhGVSP2PBsp59ZIvE5JW3UT12G+bIh9a+veNaExzcoIQYPfb+VJlytvDA21TC/4Ju2gFNwcxeVWm6etkTSUfvsMMYGsUc6+wPY=
    # overwrite: true
    # file_glob: true
    # file: "${TRAVIS_BUILD_DIR}/artifacts/*.whl"
    # on:
      # repo: tharen/PyFVS
      # tags: true

  # # Amazon S3 Storage
  # - provider: s3
    # skip_cleanup: true
    # access_key_id: AKIAIDXNPYH254RADH4A
    # secret_access_key:
      # secure: lmFYrGZSd7JpeNCRV0BU0t9ipav/Dg1JK3PX94Wz8y03ymlrGaVjvdUyokdf+fXwFeWb+B4aulU1bI2EW4vv6+U4rm0TPsIHf6myyhXftoKxLydhKDi2H4TRSaaJt6dNABSM156stqYFPSD/TtIZfCa63qZjfkK+RlNGe1WdJ16nhd57M9B/TO0A7Nq6X3TvaVKuL0yGTi8L8cfD3aumbk3ReoD/1bXjYReAteKc5lrWmyxHRyPZyrE2xhrtjTBm88GdXv/LFkeopTC2y2eLD1h2cTCOurBw1RFlxvXBshnLULDlrNkzTCGF6O5aCx7icfXCuNAcgZidYSutziXyWt69NYxlwD/Elqh0coKxnrDaMp/dj84P89DLqA+MyhcXlw2Kf2npLtLgpW1wpBXIGWDRAv1GtJHd+IjabE5htdVz6nhlONsCI/rdHN33rTvgnwiQn3Ypg9dp7vt1JFVYFImdWrflR5CH/sAJAH30FKgerVaHOHty52O/8KXkYggxzCJIOVXb7nmgJSgk/EgGeoI0t8oieudXp/J20+uTAKm3lDwtOCpoVHbi0YSWJgP8Z5KoSMq5AVWubFYxclUwDd/xwjhhN1wZ/YVQIZ4xG8dP33+ZkodZ46AX0u+IwI2REsV0t03nG0FtwXWETcCb8SWvdqGqJCHNEcHeL/yG28A=
    # region: us-west-2
    # bucket: free5
    # local-dir: ${TRAVIS_BUILD_DIR}/artifacts
    # upload-dir: pyfvs/$TRAVIS_BRANCH
    # acl: public_read
    # on:
      # repo: tharen/PyFVS
      # all_branches: true
