language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  
env:
  global:
    - FVS_STATUS=alpha
    - BUILD_ROOT=${TRAVIS_BUILD_DIR}/bin/build

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports
    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full

install:
  # Use miniconda in travis-ci http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create an environment and install dependencies
  - conda create -q -n pyfvs python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate pyfvs
  # Define the name to be used for the archive of compiled products.
  - export ARCHIVE_NAME=open-fvs-${TRAVIS_TAG}-Python${TRAVIS_PYTHON_VERSION}_64-${TRAVIS_OS_NAME}-ci.zip

script:
  - source .travis-ci/configure.sh
  - cd ${BUILD_ROOT} && make -j2 install 2> build_err.log
  
  # Run unit tests
  - source ${TRAVIS_BUILD_DIR}/.travis-ci/run_tests.sh
  
after_failure:
  # Push error logs to the console output
  - "cat ${BUILD_ROOT}/build_err.log"
  - "cat ${BUILD_ROOT}/f2py_pnc.log"

after_success:
  - ls ${BUILD_ROOT}/Open-FVS
  - cd ${BUILD_ROOT} && 7z a -bd ${ARCHIVE_NAME} Open-FVS/*
  - ls ${BUILD_ROOT}

deploy:
  - provider: releases
    skip_cleanup: true
    prerelease: true
    api_key:
      secure: cIv7F5Si2yS3QcL3bOu5QwTZdi/WiwsNhsS7+IL1LklXGKzBlzN1Df833+u1mzk1XN3VKafzrsAQ5UoshAcaN6TB6kE9FCBAGt/NO+BQJJcLr8Ig4NwU82cVQmnt8ata6t8MmNcPtRsqA4TUsd2Mvo2CKpeiZOMRo1JqasMElHqW4vh8Dbklsk4cd4zcvAOfnVT0qQC1Hzkgh0IzmB7y6dsaUOYoHbDVSMnkp+6j+yIZnWsGBsowXf7CF7hKQMMXiXbl5YGEMUob1OnOBw54xj5eM9Ax9mpYiyymvE+QKHj5nP1fkQoW89tgzcem53TK9qcSN+E3yApd0aK1Z11VVqIBvif7c1YmaL0w9uMv7reDnJ6zCS63GGO3nBLKUTrEo2xjrDsLpQRtK2sHYLG4JPtGB9ojzloTe0YLgemjf5bwmVWvyycVtMF0DZABnL5JWMqG9ogUA2CcNDHBqRyArcg5qkzC8LBGR5XG8V71O6M3QZVsCP+6NfxFAUGvKO3i36TQjOCMuWQdhmp75VaCH/B1o2B+UVMr7ekI4i0m16KP7JG4+47BSyPDUD7QLR0k055ext/F+RonBVtL8dpbQzZ3bASWQ/iW00tz910LanCFLRGAhUSe+bUISVsVQSltpqgV3j64OM3wC/LIyO4YSTyEx8NTTC+IRBfOgMc4ed0=
    file: ${BUILD_ROOT}/${ARCHIVE_NAME}
    on:
      repo: tharen/PyFVS
      tags: true

  # Amazon S3 Storage
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAIDXNPYH254RADH4A
    secret_access_key:
      secure: lmFYrGZSd7JpeNCRV0BU0t9ipav/Dg1JK3PX94Wz8y03ymlrGaVjvdUyokdf+fXwFeWb+B4aulU1bI2EW4vv6+U4rm0TPsIHf6myyhXftoKxLydhKDi2H4TRSaaJt6dNABSM156stqYFPSD/TtIZfCa63qZjfkK+RlNGe1WdJ16nhd57M9B/TO0A7Nq6X3TvaVKuL0yGTi8L8cfD3aumbk3ReoD/1bXjYReAteKc5lrWmyxHRyPZyrE2xhrtjTBm88GdXv/LFkeopTC2y2eLD1h2cTCOurBw1RFlxvXBshnLULDlrNkzTCGF6O5aCx7icfXCuNAcgZidYSutziXyWt69NYxlwD/Elqh0coKxnrDaMp/dj84P89DLqA+MyhcXlw2Kf2npLtLgpW1wpBXIGWDRAv1GtJHd+IjabE5htdVz6nhlONsCI/rdHN33rTvgnwiQn3Ypg9dp7vt1JFVYFImdWrflR5CH/sAJAH30FKgerVaHOHty52O/8KXkYggxzCJIOVXb7nmgJSgk/EgGeoI0t8oieudXp/J20+uTAKm3lDwtOCpoVHbi0YSWJgP8Z5KoSMq5AVWubFYxclUwDd/xwjhhN1wZ/YVQIZ4xG8dP33+ZkodZ46AX0u+IwI2REsV0t03nG0FtwXWETcCb8SWvdqGqJCHNEcHeL/yG28A=
    region: us-west-2
    bucket: free5
    local-dir: ${BUILD_ROOT}/Open-FVS
    upload-dir: travis-builds
    acl: public_read
    on:
      repo: tharen/PyFVS
