language: python

python:
  - "2.7"
    
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports

    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full
    
script:
  - mkdir -p bin/build
  - cd bin/build && cmake -G"Unix Makefiles" .. -DFVS_VARIANTS="pnc;wcc" -DWITH_PYMOD=Yes -DCMAKE_SYSTEM_NAME=Linux
  - cd bin/build && make -j2
