language: python
python:
- '2.7'
env:
  global:
  - FVS_STATUS=alpha
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports
    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full

script:
- mkdir -p bin/build
- cd ${TRAVIS_BUILD_DIR}/bin/build && cmake -G"Unix Makefiles" .. -DFVS_VARIANTS="pnc;wcc"
  -DWITH_PYMOD=Yes -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_INSTALL_PREFIX=Open-FVS
- cd ${TRAVIS_BUILD_DIR}/bin/build && make -j2
- cd ${TRAVIS_BUILD_DIR}/bin/build && make install

after_success:
- cd ${TRAVIS_BUILD_DIR}/bin
- 7z a -bd open-fvs_${TRAVIS_TAG}-${FVS_STATUS}.zip Open-FVS/*

deploy:
  provider: releases
  api_key:
    secure: tBbPX/kELwmJlxO/2YgqZfYM80DMnTr2z+pz0ukCR7hBakxkHnrJXrfsm479kStdEmOAekxHB7K3PiDNq+gVzj0xJBcGy8uAmh7LAGfdjLV7YGzfAFTYzCFOFu6Fc9dU8o+cn4nP33sePzbJ7HEyS8GMLWsLEDYGCeE1s0TF8tUF0zo+YdkAeZSno0zvZh5EvzUdB7j6XCJzYRYzzTvz0k2i8wgdc4sOty82yCECBuNsbxnHz3GzZ/HBOd9vTEFERDPOeyhJsXbjOQgfjK+gpeWYkFSR2B8YUqvk7jJhUqRtR3Ti9HlPRFx9uuTcRSEAF8WcdMzYXIf6kfh1wKEzsU4heZRaPB6aLHeQhy9bfWEeE550XYOskLQQZOGfA76Vts00sp8Z361CYOhiyY0WCYLzrLjH0Q2NtFhduBl3xmHt3+jXDA1zFrEhc4Ur1fdvAwjoJkupdXZtRHXn8Q+N7+QRV3NEAEMI2XtfAcT8IwHREyGEqQtKERwAFJFuU0/nKcxCJE1nDxO/MvJAKtSIjFovZMMidaJBnJpP8m710gHjvecbSNkKdcGQlT+Yx61WTP8tURrLgLoS4hqHfHsIeJI6R+mknUUlC8HBGdpjRl0eL7+TCm4IMsF6B2O5Iy/QBRuPKZ+HkHUy4ZJAAeaMAGLRByMyXY850YWiRLs08eg=
  file: bin/open-fvs_${TRAVIS_TAG}-${FVS_STATUS}.zip
  on:
    repo: tharen/testing
