language: python
python:
- '2.7'
- '3.5'

env:
  global:
  - FVS_STATUS=alpha
  - BUILD_ROOT=${TRAVIS_BUILD_DIR}/bin/build
  
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports
    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full

# Use miniconda 
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt

script:
- mkdir -p ${BUILD_ROOT}
- cd ${BUILD_ROOT} && cmake -G"Unix Makefiles" .. -DFVS_VARIANTS=pnc
  -DWITH_PYMOD=Yes -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_INSTALL_PREFIX=Open-FVS
- cd ${BUILD_ROOT} && make -j2 2> build_err.log
- cd ${BUILD_ROOT} && make install 2>> build_err.log
  
after_failure:
- "cat ${BUILD_ROOT}/build_err.log"
- "cat ${BUILD_ROOT}/f2py_pnc.log"

after_success:
- cd ${BUILD_ROOT} && 7z a -bd open-fvs_${TRAVIS_TAG}-${FVS_STATUS}.zip Open-FVS/*
- ls ${BUILD_ROOT}
- ls ${BUILD_ROOT}/Open-FVS

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: tBbPX/kELwmJlxO/2YgqZfYM80DMnTr2z+pz0ukCR7hBakxkHnrJXrfsm479kStdEmOAekxHB7K3PiDNq+gVzj0xJBcGy8uAmh7LAGfdjLV7YGzfAFTYzCFOFu6Fc9dU8o+cn4nP33sePzbJ7HEyS8GMLWsLEDYGCeE1s0TF8tUF0zo+YdkAeZSno0zvZh5EvzUdB7j6XCJzYRYzzTvz0k2i8wgdc4sOty82yCECBuNsbxnHz3GzZ/HBOd9vTEFERDPOeyhJsXbjOQgfjK+gpeWYkFSR2B8YUqvk7jJhUqRtR3Ti9HlPRFx9uuTcRSEAF8WcdMzYXIf6kfh1wKEzsU4heZRaPB6aLHeQhy9bfWEeE550XYOskLQQZOGfA76Vts00sp8Z361CYOhiyY0WCYLzrLjH0Q2NtFhduBl3xmHt3+jXDA1zFrEhc4Ur1fdvAwjoJkupdXZtRHXn8Q+N7+QRV3NEAEMI2XtfAcT8IwHREyGEqQtKERwAFJFuU0/nKcxCJE1nDxO/MvJAKtSIjFovZMMidaJBnJpP8m710gHjvecbSNkKdcGQlT+Yx61WTP8tURrLgLoS4hqHfHsIeJI6R+mknUUlC8HBGdpjRl0eL7+TCm4IMsF6B2O5Iy/QBRuPKZ+HkHUy4ZJAAeaMAGLRByMyXY850YWiRLs08eg=
  file: ${BUILD_ROOT}/open-fvs_${TRAVIS_TAG}-${FVS_STATUS}.zip
  on:
    repo: tharen/testing
    tags: true
