version: 0.0.{build}

init:
  # Display remote desktop details
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
    - set MSYSTEM=MINGW64
    - set CHERE_INVOKING=1
    # - pacman --noconfirm -Syu
    # - pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel
    # - pacman --noconfirm -Su
    # # - pacman --noconfirm -Sy
    # - pacman --noconfirm -S mingw-w64-x86_64-gcc
    # - pacman --noconfirm -S mingw-w64-x86_64-gcc-fortran
    # - pacman --noconfirm -S mingw-w64-x86_64-cmake
    
build_script:
    ps: >-
      bash --login -c @"
        cd /c/projects/testing
        ./configure_appveyor.sh
        cd /c/projects/testing/bin
        make -f makefile_all all
        make -f makefile_all bundle
      "@
    # ps: bash ./configure_appveyor.sh
    # - bash ./configure_appveyor.sh
    # - bash -c "cd bin && make -f makefile_all all"
    # - c:\msys64\usr\bin\sh.exe --login -c "cd /c/projects/testing && ./configure_appveyor.sh"
    # - c:\msys64\usr\bin\sh.exe --login -c "cd /c/projects/testing/bin && make -f makefile_all"

on_finish:
  # Pause the build for remote desktop access
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))