version: 0.0.{build}

init:
  # Display remote desktop details
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    - set PATH=C:\MinGW\bin;C:\7z\bin;C:\Windows\System32;C:\Windows
    
build_script:
    - .appveyor\configure_appveyor.bat

after_build:
    - pushd bin
    - 7z a -bd open-fvs.zip Open-FVS\*
    - popd

artifacts:
    - path: bin\open-fvs.zip
      name: open-fvs
      type: zip
    
on_finish:
  # Pause the build for remote desktop access
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))