install:
    - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
    - set MSYSTEM=MINGW64

build_script:
    ps: >-
      bash -c @"
        which cmake
        ./configure_appveyor.sh
        make -f makefile_all all
        make -f makefile_all bundle
      "@
      